#!/usr/bin/env python3
"""Generate Annotation Sans Regular from Liberation Sans Regular 2.1.5.

Requires Pillow and a shared FreeType library only when regenerating the data.
See devnotes/annotation-font.md for the source font and license.
"""

import argparse
import ctypes
import ctypes.util
import hashlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, features

FONT_SHA256 = "76d04c18ea243f426b7de1f3ad208e927008f961dc5945e5aad352d0dfde8ee8"
FONT_SIZE = 29
FONT_HEIGHT = 28
FIRST_CHAR = 32
LAST_CHAR = 126


class Vector(ctypes.Structure):
    _fields_ = [("x", ctypes.c_long), ("y", ctypes.c_long)]


def kerning_pairs(font_path, library_path, advances):
    library_path = library_path or ctypes.util.find_library("freetype")
    if not library_path:
        raise ValueError("FreeType was not found; supply its path with --freetype")
    ft = ctypes.CDLL(library_path)
    ft.FT_Init_FreeType.argtypes = [ctypes.POINTER(ctypes.c_void_p)]
    ft.FT_New_Face.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_long,
                             ctypes.POINTER(ctypes.c_void_p)]
    ft.FT_Set_Pixel_Sizes.argtypes = [ctypes.c_void_p, ctypes.c_uint, ctypes.c_uint]
    ft.FT_Get_Char_Index.argtypes = [ctypes.c_void_p, ctypes.c_ulong]
    ft.FT_Get_Char_Index.restype = ctypes.c_uint
    ft.FT_Get_Kerning.argtypes = [ctypes.c_void_p, ctypes.c_uint, ctypes.c_uint,
                                ctypes.c_uint, ctypes.POINTER(Vector)]
    ft.FT_Done_Face.argtypes = [ctypes.c_void_p]
    ft.FT_Done_FreeType.argtypes = [ctypes.c_void_p]
    library, face = ctypes.c_void_p(), ctypes.c_void_p()

    def check(result):
        if result:
            raise ValueError(f"FreeType error {result}")

    check(ft.FT_Init_FreeType(ctypes.byref(library)))
    try:
        check(ft.FT_New_Face(library, str(font_path).encode(), 0, ctypes.byref(face)))
        check(ft.FT_Set_Pixel_Sizes(face, 0, FONT_SIZE))
        indices = {c: ft.FT_Get_Char_Index(face, c) for c in range(FIRST_CHAR, LAST_CHAR + 1)}
        pairs = []
        for first, left in indices.items():
            for second, right in indices.items():
                vector = Vector()
                check(ft.FT_Get_Kerning(face, left, right, 0, ctypes.byref(vector)))
                if vector.x % 64:
                    raise ValueError("Expected grid-fitted pixel kerning")
                adjust = vector.x // 64
                if not (-128 <= adjust <= 127 and advances[second] + adjust > 0):
                    raise ValueError("Kerning exceeds the embedded font's metric range")
                if adjust:
                    pairs.append(((first << 8) | second, adjust))
        return pairs
    finally:
        if face:
            ft.FT_Done_Face(face)
        ft.FT_Done_FreeType(library)


def generate(font_path, freetype):
    if hashlib.sha256(font_path.read_bytes()).hexdigest() != FONT_SHA256:
        raise ValueError("Expected LiberationSans-Regular.ttf from Liberation Fonts 2.1.5")
    font = ImageFont.truetype(str(font_path), FONT_SIZE, layout_engine=ImageFont.Layout.BASIC)
    codes = range(FIRST_CHAR, LAST_CHAR + 1)
    boxes = [font.getbbox(chr(c), anchor="ls") for c in codes]
    baseline = -min(box[1] for box in boxes)
    if baseline + max(box[3] for box in boxes) > FONT_HEIGHT:
        raise ValueError("Glyphs exceed the annotation line height")
    glyphs, pixels, advances = [], bytearray(), {}
    for code, (left, top, right, bottom) in zip(codes, boxes):
        image = Image.new("L", (max(1, right - left), FONT_HEIGHT))
        ImageDraw.Draw(image).text((-left, baseline), chr(code), font=font, fill=255, anchor="ls")
        advance = round(font.getlength(chr(code)))
        advances[code] = advance
        bounds = image.getbbox()
        if bounds:
            x0, y0, x1, y1 = bounds
            glyphs.append((len(pixels), x1 - x0, y1 - y0, left + x0, y0, advance))
            pixels.extend(image.crop(bounds).tobytes())
        else:
            glyphs.append((len(pixels), 0, 0, 0, 0, advance))
    pairs = kerning_pairs(font_path, freetype, advances)
    lines = [
        "// Generated by tools/generate_annotation_font.py; do not edit by hand.",
        "// Annotation Sans Regular, derived from Liberation Sans Regular 2.1.5.",
        "// Digitized data copyright (c) 2010 Google Corporation.",
        "// Copyright (c) 2012 Red Hat, Inc.",
        "// Font data licensed under SIL OFL 1.1; see licenses/AnnotationSans_LICENSE.",
        f"// Source font SHA-256: {FONT_SHA256}",
        f"// Rasterized at {FONT_SIZE}px; baseline {baseline}; FreeType {features.version_module('freetype2')}.",
        "", "#ifndef RTENGINE_FNTDAT_H", "#define RTENGINE_FNTDAT_H", "",
        "#include <stdint.h>", "",
        f"#define ANNOTATION_FONT_HEIGHT {FONT_HEIGHT}",
        f"#define ANNOTATION_FIRST_CHAR {FIRST_CHAR}",
        f"#define ANNOTATION_LAST_CHAR {LAST_CHAR}", "",
        "typedef struct {", "    uint32_t offset;", "    uint8_t width;",
        "    uint8_t height;", "    int8_t left;", "    uint8_t top;",
        "    uint8_t advance;", "} AnnotationGlyph;", "",
        f"static const AnnotationGlyph annotation_glyphs[{len(glyphs)}] = {{",
    ]
    for code, glyph in zip(codes, glyphs):
        lines.append("    {" + ", ".join(map(str, glyph)) + f"}}, // U+{code:04X}")
    lines.extend(["};", "", "// Row-major 8-bit coverage, cropped to each glyph's ink bounds.",
                  f"static const uint8_t fntdat[{len(pixels)}] = {{"])
    for offset in range(0, len(pixels), 20):
        lines.append("    " + ", ".join(f"0x{v:02x}" for v in pixels[offset:offset + 20]) + ",")
    lines.extend(["};", "", "// Grid-fitted kerning at the same font size, in pixels.",
                  "typedef struct {", "    uint16_t pair;", "    int8_t adjust;",
                  "} AnnotationKerning;", "",
                  f"static const AnnotationKerning annotation_kerning[{len(pairs)}] = {{"])
    lines.extend(f"    {{{pair}, {adjust}}}," for pair, adjust in pairs)
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("font", type=Path)
    parser.add_argument("--freetype", help="Path to the FreeType shared library")
    parser.add_argument("--output", type=Path,
                        default=Path(__file__).resolve().parents[1] / "rtengine/fntdat.h")
    args = parser.parse_args()
    args.output.write_text(generate(args.font, args.freetype), encoding="utf-8")


if __name__ == "__main__":
    main()
