name: macOS Build
on:
  push:
    branches:
      - minitest
  pull_request:
  workflow_dispatch:
jobs:
  armtest2:
    runs-on: macos-14
    steps:
      - name: Test-launch the app 2
        run: |
          curl -L https://github.com/Benitoite/RawTherapee/releases/download/nightly-github-actions/RawTherapee_dev_macOS_arm64_Release.zip -o rt.zip
          unzip rt.zip
          ls
          cd RawTherapee*
          ls
          yes qy | hdiutil attach *dmg
          cd /Volumes/RawTherapee*
          sudo cp -r RawTherapee.app /Applications
          cd
          # Codesign the app
          curl -L https://raw.githubusercontent.com/Benitoite/RawTherapee/minitest/tools/osx/ci.entitlements -o 1ci.entitlements
          iconv -f UTF-8 -t ASCII 1ci.entitlements > ci.entitlements
          plutil -convert xml1 ci.entitlements
          for frame in /Applications/RawTherapee.app/Contents/Frameworks/* ; do
              echo $frame
              sudo codesign --preserve-metadata=identifier --digest-algorithm=sha1,sha256 --force -v -s "-" -i com.rawtherapee.RawTherapee --entitlements ci.entitlements $frame
          done
          for resource in /Applications/RawTherapee.app/Contents/Resources/* ; do
              echo $resource
              if [ ! -d $resource ]; then
                  sudo codesign --preserve-metadata=identifier --digest-algorithm=sha1,sha256 --force -v -s "-" -i com.rawtherapee.RawTherapee --entitlements ci.entitlements $resource
              else
                  for subresource in /Applications/RawTherapee.app/Contents/Resources/$(basename $resource)/* ; do
                      if [ ! -d $subresource ]; then
                          sudo codesign --preserve-metadata=identifier --digest-algorithm=sha1,sha256 --force -v -s "-" -i com.rawtherapee.RawTherapee --entitlements ci.entitlements $subresource
                      fi
                  done
              fi
          done
          sudo codesign --preserve-metadata=identifier --digest-algorithm=sha1,sha256 --force -v -s "-" -i com.rawtherapee.RawTherapee --entitlements ci.entitlements /Applications/RawTherapee.app/Contents/MacOS/rawtherapee-cli
          sudo codesign --preserve-metadata=identifier --digest-algorithm=sha1,sha256 --force -v -s "-" -i com.rawtherapee.RawTherapee --entitlements ci.entitlements /Applications/RawTherapee.app/Contents/MacOS/rawtherapee
          sudo codesign --preserve-metadata=identifier --digest-algorithm=sha1,sha256 --force -v -s "-" -i com.rawtherapee.RawTherapee --entitlements ci.entitlements /Applications/RawTherapee.app

          open -a /Applications/RawTherapee.app
          sleep 5
          osascript -e 'tell application "Finder"' -e 'get the name of every process whose visible is true' -e 'end tell'
          osascript -e 'tell application "RawTherapee" to if it is running then quit'
