
name: macOS Build
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Test-launch the app
        run: |
          curl -L https://rawtherapee.com/shared/builds/mac/RawTherapee_macOS_13.3_Universal_5.10.zip
          unzip RawTherapee_macOS_13.3_Universal_5.10.zip
          cd RawTherapee*
          open *.dmg
          cd /Volumes/RawTherapee*
          cp -r RawTherapee.app /Applications
          open -a RawTherapee
          sleep 5
          osascript -e 'tell application "Finder"' -e 'get the name of every process whose visible is true' -e 'end tell'
          osascript -e 'tell application "RawTherapee" to if it is running then quit'
