name: Windows Build
on:
  push:
    branches:
      - dev
      - wintimer
      - releases
      - 'release-[0-9]+.*'
    tags:
      - '[0-9]+.*'
  pull_request:
    branches:
      - dev
      - wintimer
      - releases
      - 'release-[0-9]+.*'
  workflow_dispatch:

env:
  publish_pre_dev_labels: '[]'


jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        build_type: [release]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          location: C:\msys2
          update: true
          msystem: MINGW64
          install: |
            git
            intltool
          pacboy: |
            cc:p
            pkgconf:p
            cmake:p
            autotools:p
            ninja:p
            gtkmm3:p
            lcms2:p
            fftw:p
            lensfun:p
            libiptcdata:p
            libjxl:p
            exiv2:p

      - name: Configure build
        run: |
          export REF_NAME_FILTERED="$(echo '${{github.ref_name}}' | sed 's/[^A-z0-9_.-]//g')"

          if [ '${{github.ref_type}}' == 'tag' ]; then
            export CACHE_SUFFIX=""
          else
            echo "Setting cache suffix."
            export CACHE_SUFFIX="5-$REF_NAME_FILTERED"
            echo "Cache suffix is '$CACHE_SUFFIX'."
          fi

          echo "Running CMake configure."
          cmake \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE='${{matrix.build_type}}' \
            -DCACHE_NAME_SUFFIX="$CACHE_SUFFIX" \
            -DPROC_TARGET_NUMBER="11" \
            -DWITH_LTO="OFF" \
            -DLENSFUNDBDIR="share/lensfun" \
            -S . -B build

          echo "Recording filtered ref name."
          echo "REF_NAME_FILTERED=$REF_NAME_FILTERED" >> "$(cygpath -u $GITHUB_ENV)"

      - name: Build RawTherapee
        run: |
          echo "Running CMake install."
          cmake --build build --target install -j 4 

      - name: Include Lensfun
        run: |
          echo "Updating Lensfun database."
          lensfun-update-data
          echo "Creating Lensfun directory in the build directory."
          mkdir -p 'build/${{matrix.build_type}}/share'
          echo "Copying Lensfun database to the build directory."
          cp -R "/C/msys2/msys64/mingw64/var/lib/lensfun-updates/version_1" 'build/${{matrix.build_type}}/share/lensfun'

      - name: Bundle dependencies
        run: |
          echo "Listing shared library dependencies."
          ldd "./build/${{matrix.build_type}}/rawtherapee.exe"
          echo "Finding DLLs to include."
          DLLS=($(ldd "./build/${{matrix.build_type}}/rawtherapee.exe" | grep '/mingw64/bin/' | awk '{print($1)'}))
          echo "Required DLLs are: ${DLLS[*]}"

          echo "Getting workspace path."
          export BUILD_DIR="$(pwd)/build/${{matrix.build_type}}"
          echo "Build directory is '$BUILD_DIR'."
          echo "Changing working directory to MSYS2 MINGW64."
          cd "/C/msys2/msys64/mingw64"
          echo "Copying DLLs and EXEs."

          cd ./bin
          cp \
            "gdbus.exe" \
            "gspawn-win64-helper.exe" \
            "gspawn-win64-helper-console.exe" \
            ${DLLS[*]} \
            "$BUILD_DIR"
          cd -

          echo "Copying Adwaita theme."
          mkdir -p "$BUILD_DIR/share/icons/Adwaita"
          cd 'share/icons/Adwaita/'
          mkdir -p "$BUILD_DIR/share/icons/Adwaita/symbolic"
          cp -r \
            "symbolic/actions" \
            "symbolic/devices" \
            "symbolic/mimetypes" \
            "symbolic/places" \
            "symbolic/status" \
            "symbolic/ui" \
            "$BUILD_DIR/share/icons/Adwaita/symbolic"
          cp 'index.theme' "$BUILD_DIR/share/icons/Adwaita"
          cd -

          echo "Copying GDK pixbuf."
          mkdir -p "$BUILD_DIR/lib"
          cp -r 'lib/gdk-pixbuf-2.0' "$BUILD_DIR/lib/gdk-pixbuf-2.0"

          echo "Copying GLib schemas."
          mkdir -p "$BUILD_DIR/share/glib-2.0/schemas"
          cp 'share/glib-2.0/schemas/gschemas.compiled' "$BUILD_DIR/share/glib-2.0/schemas"

          echo "Creating GTK settings.ini."
          mkdir -p "$BUILD_DIR/share/gtk-3.0/"
          echo -e '[Settings]\ngtk-button-images=1' > "$BUILD_DIR/share/gtk-3.0/settings.ini"

      - name: Timing test
        run: |
          cd build/${{matrix.build_type}}
          git clone https://github.com/Benitoite/raw-test .\raw-test
          ls .\raw-test
          $t=0
          $n=5
          $x = 0; for ($i = 0; $i -lt $n; $i++) { $x+=(Measure-Command { .\rawtherapee-cli.exe | grep TotalMilliseconds).Split(' ')[2] } }; $t+=($x/$n)
          $x = 0; for ($i = 0; $i -lt $n; $i++) { $x+=(Measure-Command { .\rawtherapee-cli.exe -j -s -Y -c .\raw-test\typewriter.CR2 | grep TotalMilliseconds).Split(' ')[2] } }; $t+=($x/$n)
          $x = 0; for ($i = 0; $i -lt $n; $i++) { $x+=(Measure-Command { .\rawtherapee-cli.exe -j -s -Y -c .\raw-test\naturalbridges.CR2 | grep TotalMilliseconds).Split(' ')[2] } }; $t+=($x/$n)
          $x = 0; for ($i = 0; $i -lt $n; $i++) { $x+=(Measure-Command { .\rawtherapee-cli.exe -j -s -Y -c .\raw-test\beachcabin.ARW | grep TotalMilliseconds).Split(' ')[2] } }; $t+=($x/$n)
          echo $t
        shell: pwsh
